### ISSUE TITLE
Convert IP address/mask to a network/mask

### ISSUE THREAD

**Issue by jkeane100** [dmulyalin/ttp_templates#6]
Dear all. 

Pardon my ignorance. I am trying to parse the following and extract the network/mask from an ip address/mask

interface Vlan100
 description vl100
 ip address 192.168.10.1/24
 ip vrf fredfred 
!

with:

interface {{ ifname }}
 description {{ if-descr }}
 ip address {{ prefix | to_net }}

however I get an error message stating 192.168.10.1/24 has host bits set"

I now understand that that to_net is not defined to provide a network/mask from an ip address/mask.

**My question is**: is there a build in method that will allow me to do that or do I need to create a macro to acheive the result.

jkeane100

**Comment by dmulyalin** [comment]
Hi, checkout this function - https://ttp.readthedocs.io/en/latest/Match%20Variables/Functions.html#to-ip

would this do what you loking for?:
```
<input load="text">
interface Loopback0
 ip address 1.0.0.3/32
!
interface Vlan777
 ip address 192.168.0.1/24
!
</input>

<group name="interfaces">
interface {{ interface }}
 ip address {{ ip | to_ip | network | to_str }}
</group>
```

Result:
```
[
	[
		{
			"interface": "Loopback0",
			"ip": "1.0.0.3/32"
		},
		{
			"interface": "Vlan777",
			"ip": "192.168.0.0/24"
		}
	]
]
```

`to_ip` converts ip address to ipaddress.IPv4Interface object which has `network` attribute referring to IPv4Netbowrk object, referencing that attribute and passing it though `to_str` function produces string representation of the network.
